apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mailer 
    spec:
      containers:
        - name: mailer 
          image: mailerregistry.azurecr.io/mailer
          ports:
          - containerPort: 80
